version: "3.8"
services:
  pg:
    image: postgres:15
    environment:
      POSTGRES_DB: jaramgle
      POSTGRES_USER: jaramgle
      POSTGRES_PASSWORD: jaramgle
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
