CREATE TABLE IF NOT EXISTS users(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email VARCHAR(191) NOT NULL,
    password_hash VARCHAR(200) NOT NULL,
    nickname VARCHAR(64),
    provider VARCHAR(255),
    email_verified BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_users_email ON users(email);

ALTER TABLE users ADD COLUMN IF NOT EXISTS password_hash VARCHAR(200);
ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified BOOLEAN DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS provider VARCHAR(255);
