-- Story table
CREATE TABLE stories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    age_range VARCHAR(50),
    topics_json TEXT, -- Store as JSON string
    language VARCHAR(10),
    length_level VARCHAR(50),
    status VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_stories_user_id ON stories(user_id);

-- StoryPage table
CREATE TABLE story_pages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    story_id BIGINT NOT NULL,
    page_no INT NOT NULL,
    text TEXT NOT NULL,
    FOREIGN KEY (story_id) REFERENCES stories(id) ON DELETE CASCADE,
    UNIQUE (story_id, page_no)
);

-- StorageQuota table
CREATE TABLE storage_quotas (
    user_id VARCHAR(255) PRIMARY KEY,
    limit_cnt INT NOT NULL DEFAULT 10,
    used_cnt INT NOT NULL DEFAULT 0,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);