CREATE TABLE tests (
    code VARCHAR(255) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    version INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE questions (
    id VARCHAR(255) PRIMARY KEY,
    test_code VARCHAR(255) NOT NULL,
    body CLOB NOT NULL, -- TEXT in H2 is CLOB
    is_reverse BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (test_code) REFERENCES tests(code)
);

CREATE TABLE answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- H2 specific identity
    question_id VARCHAR(255) NOT NULL,
    "value" INT NOT NULL,
    submission_id VARCHAR(255) NOT NULL,
    FOREIGN KEY (question_id) REFERENCES questions(id)
);

CREATE TABLE profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) UNIQUE NOT NULL,
    traits TEXT, -- JSONB -> TEXT
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
