CREATE TABLE characters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(128) NOT NULL,
    persona VARCHAR(512),
    catchphrase VARCHAR(256),
    prompt_keywords VARCHAR(512),
    image_path VARCHAR(256),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE story_characters (
    story_id BIGINT NOT NULL,
    character_id BIGINT NOT NULL,
    PRIMARY KEY (story_id, character_id),
    CONSTRAINT fk_story_char_story FOREIGN KEY (story_id) REFERENCES stories(id) ON DELETE CASCADE,
    CONSTRAINT fk_story_char_character FOREIGN KEY (character_id) REFERENCES characters(id) ON DELETE CASCADE
);

INSERT INTO characters (slug, name, persona, catchphrase, prompt_keywords, image_path) VALUES
 ('lulu-rabbit', '루루 토끼', '호기심 많고 씩씩하지만 가끔 덤벙대는 하얀 토끼', '"깡충깡충! 내가 먼저 가볼래!"', 'cute white rabbit, big ears, blue ribbon, bright expression, storybook illustration', '/characters/lulu-rabbit.png'),
 ('mungchi-puppy', '뭉치 강아지', '친근하고 항상 웃음 가득한 노란 강아지', '"멍멍! 신나는 일이 또 없을까?"', 'yellow puppy, round ears, wagging tail, cheerful face, kids illustration', '/characters/mungchi-puppy.png'),
 ('coco-squirrel', '코코 다람쥐', '먹을 걸 좋아하지만 친구들과 잘 나누는 갈색 다람쥐', '"냠냠~ 도토리는 사랑이야!"', 'brown squirrel, chubby cheeks, acorn, lively storybook style', '/characters/coco-squirrel.png'),
 ('ria-princess', '별빛 공주 리아', '상냥하지만 모험심 강한 금발의 공주', '"내가 지켜줄게, 반짝반짝!"', 'princess, blonde hair, star hairpin, pink dress, fantasy storybook', '/characters/ria-princess.png'),
 ('lucas-prince', '호기심 왕자 루카스', '새로운 걸 배우길 좋아하는 장난기 많은 왕자', '"궁금한 건 꼭 알아내야 해!"', 'young prince, blue cape, small crown, playful expression, kids fantasy', '/characters/lucas-prince.png'),
 ('geo-explorer', '탐험가 지오', '두려움 없이 도전하지만 길치인 꼬마 탐험가', '"여긴 어디지? 그래도 가보자!"', 'child explorer, compass hat, map, cute adventure illustration', '/characters/geo-explorer.png'),
 ('robo-roro', '로보 로로', '계산적이지만 마음이 따뜻한 은색 로봇', '"삐빅! 친구랑 노는 게 제일 좋아."', 'cute silver robot, round heart eyes, child-friendly art', '/characters/robo-roro.png'),
 ('mimi-fairy', '몽글 요정 미미', '구름처럼 몽글몽글한 머리의 파스텔 요정', '"몽글몽글~ 걱정은 날려버려!"', 'tiny fairy, fluffy cloud hair, pastel wings, gentle illustration', '/characters/mimi-fairy.png'),
 ('pipi-math-monster', '쏙쏙 수학 괴물 피피', '숫자 문제를 좋아하며 아이들에게 퀴즈를 내는 연두색 괴물', '"1, 2, 3! 재미있는 수학 놀이터야!"', 'cute green monster, floating numbers, playful kids art', '/characters/pipi-math-monster.png'),
 ('lulu-space', '반짝 우주인 루루', '우주 여행을 동경하는 꿈 많은 아이 우주인', '"별빛처럼 반짝이는 모험으로 가자!"', 'cute kid astronaut, round helmet, star patterns, whimsical style', '/characters/lulu-space.png');
