CREATE TABLE heart_products (
    code VARCHAR(64) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description CLOB,
    hearts INT NOT NULL,
    bonus_hearts INT DEFAULT 0 NOT NULL,
    price INT NOT NULL,
    sort_order INT DEFAULT 0 NOT NULL,
    is_active BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE billing_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    product_code VARCHAR(64) NOT NULL,
    quantity INT DEFAULT 1 NOT NULL,
    price_per_unit INT NOT NULL,
    hearts_per_unit INT NOT NULL,
    bonus_hearts_per_unit INT NOT NULL,
    total_amount INT NOT NULL,
    status VARCHAR(32) NOT NULL,
    payment_key VARCHAR(128),
    pg_provider VARCHAR(64),
    requested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    paid_at TIMESTAMP,
    canceled_at TIMESTAMP,
    metadata CLOB,
    CONSTRAINT fk_billing_orders_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_billing_orders_product FOREIGN KEY (product_code) REFERENCES heart_products(code)
);

CREATE INDEX idx_billing_orders_user ON billing_orders(user_id, requested_at DESC);

CREATE TABLE heart_wallets (
    user_id BIGINT PRIMARY KEY,
    balance INT DEFAULT 0 NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_heart_wallets_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE heart_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    order_id BIGINT,
    amount INT NOT NULL,
    balance_after INT NOT NULL,
    type VARCHAR(32) NOT NULL,
    description CLOB,
    metadata CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_heart_transactions_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_heart_transactions_order FOREIGN KEY (order_id) REFERENCES billing_orders(id)
);

CREATE INDEX idx_heart_transactions_user_created_at ON heart_transactions(user_id, created_at DESC);

INSERT INTO heart_products (code, name, description, hearts, bonus_hearts, price, sort_order)
VALUES
    ('HEART_PACK_5', '하트 5개', '동화 생성용 하트 5개', 5, 0, 14000, 10),
    ('HEART_PACK_10', '하트 10개', '동화 생성용 하트 10개', 10, 1, 27000, 20),
    ('HEART_PACK_20', '하트 20개', '동화 생성용 하트 20개', 20, 4, 52000, 30);
