ALTER TABLE stories
    ADD COLUMN IF NOT EXISTS origin VARCHAR(32) DEFAULT 'SINGLE';

UPDATE stories
SET origin = 'SINGLE'
WHERE origin IS NULL OR origin = '';

ALTER TABLE stories
    ALTER COLUMN origin SET NOT NULL;

CREATE TABLE curriculums (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    weeks INT NOT NULL,
    category VARCHAR(50) NOT NULL,
    sub_topic VARCHAR(255),
    age_range VARCHAR(50),
    base_language VARCHAR(10) NOT NULL,
    generation_mode VARCHAR(20) NOT NULL DEFAULT 'ON_DEMAND',
    schedule_rule TEXT,
    next_run_at TIMESTAMP,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    default_character_ids_json TEXT,
    default_art_style VARCHAR(255),
    default_voice VARCHAR(100),
    base_language_locked BOOLEAN NOT NULL DEFAULT FALSE,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_curriculums_user_created_at ON curriculums(user_id, created_at DESC);

CREATE TABLE curriculum_weeks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curriculum_id BIGINT NOT NULL,
    week_no INT NOT NULL,
    primary_goal TEXT NOT NULL,
    sub_goals_json TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'NOT_STARTED',
    story_id BIGINT,
    current_version_no INT NOT NULL DEFAULT 0,
    continuity_stale BOOLEAN NOT NULL DEFAULT FALSE,
    auto_retry_used BOOLEAN NOT NULL DEFAULT FALSE,
    manual_retry_used BOOLEAN NOT NULL DEFAULT FALSE,
    skip_reason TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (curriculum_id, week_no),
    FOREIGN KEY (curriculum_id) REFERENCES curriculums(id) ON DELETE CASCADE,
    FOREIGN KEY (story_id) REFERENCES stories(id)
);

CREATE INDEX idx_curriculum_weeks_curriculum_status ON curriculum_weeks(curriculum_id, status);

CREATE TABLE curriculum_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curriculum_id BIGINT NOT NULL,
    week_id BIGINT NOT NULL,
    week_no INT NOT NULL,
    job_type VARCHAR(20) NOT NULL,
    status VARCHAR(30) NOT NULL,
    request_snapshot_json TEXT,
    charge_required BOOLEAN NOT NULL DEFAULT TRUE,
    charged BOOLEAN NOT NULL DEFAULT FALSE,
    refunded BOOLEAN NOT NULL DEFAULT FALSE,
    heart_amount INT NOT NULL DEFAULT 1,
    retry_of_job_id BIGINT,
    error_code VARCHAR(100),
    error_message TEXT,
    cancel_reason TEXT,
    queued_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    timeout_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (curriculum_id) REFERENCES curriculums(id) ON DELETE CASCADE,
    FOREIGN KEY (week_id) REFERENCES curriculum_weeks(id) ON DELETE CASCADE,
    FOREIGN KEY (retry_of_job_id) REFERENCES curriculum_jobs(id)
);

CREATE INDEX idx_curriculum_jobs_status_queued ON curriculum_jobs(status, queued_at);
CREATE INDEX idx_curriculum_jobs_curriculum_status ON curriculum_jobs(curriculum_id, status);

CREATE TABLE curriculum_episode_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_id BIGINT NOT NULL,
    story_id BIGINT NOT NULL,
    version_no INT NOT NULL,
    week_status VARCHAR(30) NOT NULL,
    story_text TEXT,
    asset_refs_json TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (week_id, version_no),
    FOREIGN KEY (week_id) REFERENCES curriculum_weeks(id) ON DELETE CASCADE,
    FOREIGN KEY (story_id) REFERENCES stories(id)
);

CREATE TABLE curriculum_series_memory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curriculum_id BIGINT NOT NULL UNIQUE,
    last_summary TEXT,
    character_state_json TEXT,
    covered_topics_json TEXT,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (curriculum_id) REFERENCES curriculums(id) ON DELETE CASCADE
);

CREATE TABLE curriculum_job_ledgers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL,
    action_type VARCHAR(20) NOT NULL,
    heart_transaction_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (job_id, action_type),
    FOREIGN KEY (job_id) REFERENCES curriculum_jobs(id) ON DELETE CASCADE,
    FOREIGN KEY (heart_transaction_id) REFERENCES heart_transactions(id)
);
