CREATE TABLE IF NOT EXISTS busan_story_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_source VARCHAR(80) NOT NULL,
    external_id VARCHAR(120) NOT NULL,
    source_type VARCHAR(40) NOT NULL DEFAULT 'ATTRACTION',
    title VARCHAR(255) NOT NULL,
    normalized_title VARCHAR(255),
    district VARCHAR(100),
    subtitle TEXT,
    intro TEXT,
    feature TEXT,
    origin TEXT,
    story_context TEXT,
    address TEXT,
    thumbnail_url TEXT,
    image_url TEXT,
    photo_title VARCHAR(255),
    photo_location VARCHAR(255),
    photo_keywords TEXT,
    data_sources TEXT,
    lat DOUBLE,
    lng DOUBLE,
    quality_score INT NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    last_synced_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (external_source, external_id)
);

CREATE INDEX IF NOT EXISTS idx_busan_story_sources_active_score
    ON busan_story_sources(active, quality_score DESC, title ASC);

CREATE INDEX IF NOT EXISTS idx_busan_story_sources_external_id
    ON busan_story_sources(external_id);

CREATE INDEX IF NOT EXISTS idx_busan_story_sources_district
    ON busan_story_sources(district);
