CREATE TABLE purchases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    item_code VARCHAR(255) NOT NULL,
    amount INT NOT NULL,
    status VARCHAR(64) NOT NULL, -- PAID, CANCELED
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE entitlements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    item_code VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP, -- null for permanent
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, item_code)
);
